# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Books
tagline:          'Book Blog'
description:      'Lets read!'
url:              https://www.meatvehicle.com
baseurl:          /

#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

#paginate:         1

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
