# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Books
tagline:          'Blog'
description:      'Lets read!'
url:              https://www.meatvehicle.com
relative_url:     https://www.meatvehicle.com
baseurl:          /
paginate_path:    /page:num/

#author:
#  name:           'Kenstogram'
#  url:            https://github.com/Kenstogram/

paginate:         3

#github:
#  repo:           https://github.com/Kenstogram/Kenstogram.github.io
